#!/usr/bin/env python
import rospy
from lidarnav.msg import WallState
from WallGapLocalizer import WallGapLocalizer

localizer = None

def callback(data):
    global localizer
    localizer.update(data.wall)

def main():
    global localizer
    localizer = WallGapLocalizer()

    rospy.init_node('lidar_localization')
    rospy.Subscriber("wall/state", WallState, callback)
    rospy.spin()
        
if __name__ == '__main__':
    main()

