#!/usr/bin/env python2

import math
import numpy
import cv2
import cv

import rospy
import roslib
from roslib import message

import sensor_msgs.point_cloud2 as pc2
from sensor_msgs.msg import PointCloud2
from sensor_msgs.msg import Image
from cv_bridge import CvBridge


bridge = CvBridge()

image_pub = None

res = 128


def lidar_cb(data):
    global image_pub
    global bridge

    def w(x): return int(res * x/2)
    def h(y): return int(res * (0.5-y/2))

    img = numpy.zeros((res,res,1), numpy.uint8)
    out = numpy.zeros((res,res,3), numpy.uint8)

    points = [(x,y) for x,y,_,_ in pc2.read_points(data)]

    for x,y in points:
        cv2.rectangle(img, (w(x),h(y)), (w(x), h(y)), (255,255,255), 1)


    out[:,:,0] = img[:,:,0]
    out[:,:,1] = img[:,:,0]
    out[:,:,2] = img[:,:,0]

    image_pub.publish(bridge.cv_to_imgmsg(cv.fromarray(out), "bgr8"))


def main():
    global image_pub

    rospy.init_node('lidarcenter')

    rospy.Subscriber('cloud', PointCloud2, lidar_cb)
    image_pub = rospy.Publisher('lidarcenter/image', Image)

    while not rospy.is_shutdown():
        rospy.loginfo('hello')
        rospy.sleep(1)


if __name__ == "__main__":
    main()
