#!/usr/bin/env python2

import math
import numpy
import cv2
import cv

import rospy
import roslib
from roslib import message

import sensor_msgs.point_cloud2 as pc2
from sensor_msgs.msg import PointCloud2
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
from driving.msg import Drive


bridge = CvBridge()

image_pub = None

res = 512
width = res
height = res

PI = math.pi
PI2 = math.pi/2



def lidar_cb(data):
    global image_pub
    global bridge

    def w(x): return int(res * (1.0-x/0.6))
    def h(y): return int(res * (0.5-y/2))

    img = numpy.zeros((width,height,1), numpy.uint8)
    out = numpy.zeros((width,height,3), numpy.uint8)

    points = [(x,y) for x,y,_,_ in pc2.read_points(data)]

    for x,y in ((w(x),h(y)) for x,y in points):
        if x+1 < width and y+1 < height and x >= 0 and y >= 0:
            img[x,y] = 255

    out[:,:,0] = img[:,:,0]
    out[:,:,1] = img[:,:,0]
    out[:,:,2] = img[:,:,0]


    image_pub.publish(bridge.cv_to_imgmsg(cv.fromarray(out), "bgr8"))


def main():
    global image_pub

    rospy.init_node('lidarnav')

    rospy.Subscriber('cloud', PointCloud2, lidar_cb)
    image_pub = rospy.Publisher('lidarpick/image', Image)

    while not rospy.is_shutdown():
        rospy.loginfo('hello')
        rospy.sleep(1)


if __name__ == "__main__":
    main()
