#!/usr/bin/env python2

import rospy
import roslib
from roslib import message

from sensor_msgs.msg import PointCloud2
from driving.msg import Twist

from lidarnav.msg import WallState
from WallAnalyzer import WallAnalyzer
from WallGapLocalizer import WallGapLocalizer

anaylzer = None
localizer = None
pub = None

def callback(data):
    global analyzer, localizer, pub

    analyzer.update(data)
    localizer.update(analyzer.wall_arr)

    pose = Twist()
    pose.x = localizer.location
    pose.y = analyzer.wall_ydistance
    pose.a = analyzer.wall_angle
    
    pose.header.stamp = data.header.stamp

    print "publishing"
    
    pub.publish(pose)

def main():
    global analyzer, localizer, pub

    rospy.init_node('find_gap')

    debug = rospy.get_param('~debug', False)
    pweight = rospy.get_param('~pweight', 1.)
    kweight = rospy.get_param('~kweight', 50.)
    analyzer = WallAnalyzer(debug, pweight, kweight)
    localizer = WallGapLocalizer(debug)

    rospy.Subscriber('cloud', PointCloud2, callback)
    pub = rospy.Publisher('pose', Twist)
    
    rospy.spin()

if __name__ == "__main__":
    main()

